# -*- coding: utf-8 -*-
# generated files, don't modify!
# tools are in abcdk/aruco_tools.py
dictDesc = {
  102: {'en': 'french_fries', 'fr': 'frites'},
  103: {'en': 'green beans', 'fr': 'haricots verts'},
  104: {'en': 'spinash', 'fr': 'épinards'},
  105: {'en': 'pasta', 'fr': 'pates'},
  106: {'en': 'bolognese spaghetti', 'fr': 'spaghetti bolognese'},
  107: {'en': 'couscous', 'fr': 'couscous'},
  108: {'en': 'breaded fish', 'fr': 'poisson pané'},
  109: {'en': 'smoked salmon', 'fr': 'saumon fumé'},
  110: {'en': 'fried eggs', 'fr': 'oeuf au plat'},
  111: {'en': 'boiled eggs', 'fr': 'oeuf a la coque'},
  112: {'en': 't bone', 'fr': 'cote de boeuf'},
  113: {'en': 'fajitas', 'fr': 'fajitas'},
  114: {'en': 'toasted ham and cheese', 'fr': 'croque monsieur'},
  115: {'en': 'hamburger', 'fr': 'hamburger'},
  120: {'en': 'carrots', 'fr': 'carottes'},
  121: {'en': 'tomato', 'fr': 'tomate'},
  122: {'en': 'cucumber', 'fr': 'concombre'},
  130: {'en': 'banana', 'fr': 'banane'},
  131: {'en': 'apple', 'fr': 'pomme'},
  132: {'en': 'pear', 'fr': 'poire'},
  133: {'en': 'strawberry', 'fr': 'fraise'},
  134: {'en': 'cherry', 'fr': 'cerise'},
  140: {'en': 'chocolate mousse', 'fr': 'mousse au chocolat'},
  141: {'en': 'apple_pie', 'fr': 'tarte aux pommes'},
  142: {'en': 'cake', 'fr': 'gateau'},
  143: {'en': 'candies', 'fr': 'bonbons'},
  144: {'en': 'ice cream', 'fr': 'glace'},
  145: {'en': 'brownies', 'fr': 'gateau au chocolat'},
  146: {'en': 'crepes', 'fr': 'crêpes'},
  147: {'en': 'lemon pie', 'fr': 'tarte aux citron'},
  160: {'en': 'mint with water', 'fr': "menthe a l'eau"},
  161: {'en': 'cola', 'fr': 'cola'},
  162: {'en': 'hot chocolate', 'fr': 'chocholat chaud'},
  163: {'en': 'glass of water', 'fr': "verre d'eau"},
  170: {'en': 'bread', 'fr': 'pain'},
  171: {'en': 'chocolat', 'fr': 'chocolat'},
}
nDictionaryType = 7