import cv2

def generateFontRom():
    strName = "Anonymous.png"
    #strName = "lucidagrande.jpg"
    strName = "tut4-2.png"
    im = cv2.imread( "data/" + strName)
    
    if( strName == "Anonymous.png" ):
        ox = 0; # origin
        oy = 3;
        sx=26; # size letter
        sy=32;
        ex = 1; # size interletter
        ey = 24;

    if( strName == "tut4-2.png" ):
        bHalf = 1
        if(bHalf):
            im = cv2.pyrDown( im ); # PyrDown only divide by 2
        ox = 0; # origin
        oy = 0;
        sx=16; # size letter
        sy=16;
        ex = 0; # size interletter
        ey = 0;

        if( bHalf):
            sx/=2;
            sy/=2;
    
    bRender = 0
    
    nNbrLetterOutputed = 0;
    strOut = "// generated by generate_font.py using %s\n" % strName;
    strOut += "#define LETTER_SIZE_X %d\n" % sx;
    strOut += "#define LETTER_SIZE_Y %d\n" % sy;
    strOut += "unsigned char aLetters[] = {\n";
    for j in range(16):
        for i in range(16):
            x = ox+i*(sx+ex);
            y = oy+j*(sy+ey);
            nNumLetter = j*16+i;
            if( nNumLetter>=ord('0')  ):
                nNbrLetterOutputed +=1;
                strOut += "// %d,%d: idx: %d, abs: %d: '%s'\n" % (i,j,nNbrLetterOutputed,nNumLetter,chr(nNumLetter));
                for jj in range(sy):
                    for ii in range(sx):
                        val = im[y+jj,x+ii]
                        #print( "val: %s" % val );
                        val = val[0]
                        strOut += "0x%02X, " % val;
                    strOut += "\n" % val;
                if( bRender ):
                    cv2.rectangle( im, (x, y), (x+sx, y+sy), (0,0,255));
    
    if(bRender):
        cv2.imshow( "im", im );
        cv2.waitKey(0);
        
    strOut += "};\n";
    strOut += "// %d letters outputted = %dko\n" % (nNbrLetterOutputed,nNbrLetterOutputed*sx*sy);
        
    print strOut;
    
    file = open("/tmp/fonts.c", "wt" );
    file.write( strOut );
    file.close();
    
    file = open("/tmp/fonts.h", "wt" );
    file.write( "#ifndef FONTS_H\n" );
    file.write( "#define FONTS_H\n" );
    file.write( "extern unsigned char * aLetters;\n" );
    
    file.write( "#endif // FONTS_H\n" );
    file.close();

    
# generateFontRom - end
    
    
    
    
generateFontRom();