from pathlib import Path
import sys

from PIL import Image
from pillow_heif import register_heif_opener


register_heif_opener()


def convert_heif_to_jpg(folder="."):
    path = Path(folder)

    for file in path.iterdir():
        if file.suffix.lower() not in {".heif", ".heic"}:
            continue

        output = file.with_suffix(".jpg")

        with Image.open(file) as image:
            rgb = image.convert("RGB")
            rgb.save(output, "JPEG", quality=90)


def main():
    folder = sys.argv[1] if len(sys.argv) > 1 else "."
    convert_heif_to_jpg(folder)


# generated by chatgpt, not working!
# please utilise convert_heif.py que j'avais fait avant et qui fonctionne bien
if __name__ == "__main__":
    main()